export { WelcomeSection } from './WelcomeSection'
export { HighlightsSection } from './Highlights/HighlightsSection'
export { CloserLookSection } from './CloserLook/CloserLookSection'
export { ExploreSection } from './Explore/ExploreSection'
export { ChipSection } from './Chip/ChipSection'
export { CameraSection } from './Camera/CameraSection'
export { ZoomSection } from './Zoom/ZoomSection'
export { BatterySection } from './Battery/BatterySection'